[theme]
primaryColor = "#2196F3"  # Color principal (botones, énfasis)
backgroundColor = "#F5F5F5"  # Color del fondo general
secondaryBackgroundColor = "#E1F5FE"  # Color del fondo de la barra lateral
textColor = "#212121"  # Color del texto principal
font = "Arial"  # Tipo de fuente
